App_Usuarios/urls.py
from django.urls import path
from App_Usuarios.views import registro, ingresar, logout, perfil
# perfil

urlpatterns = [
    path('signup/', registro, name='signup'),
    path('login/', ingresar, name='login'),
    path('logout/', logout, name='logout'),
    path('perfil/', perfil, name='perfil'),

]

RiskAgr/urls.py
from django.contrib import admin
from django.urls import path, include
from App_RiskCalc.views import *
from App_BlogAgri.views import *
from App_Usuarios.views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_RiskCalc.urls')),
    path('', include('App_BlogAgri.urls')),
    path('', include('App_Usuarios.urls')),
    path('about/', about, name='about'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Usuarios/models.py
from django.db import models

# Create your models here.

App_Usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    nombres = forms.CharField(max_length=30)
    apellidos = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ("username", "nombres", "apellidos", "email",
                  "password1", "password2")

    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["nombres"]
        user.last_name = self.cleaned_data["apellidos"]
        if commit:
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(required=True)
    nombres = forms.CharField(max_length=30)
    apellidos = forms.CharField(max_length=30)
    password1 = forms.CharField(
        label="Contraseña", widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(
        label="Confirmar contraseña", widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = ("username", "nombres", "apellidos",
                  "email", 'password1', 'password2')

    def save(self, commit=True):
        user = super(CustomUserChangeForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["nombres"]
        user.last_name = self.cleaned_data["apellidos"]
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 == password2:
            user.set_password(password1)

        if commit:
            user.save()
        return user

App_Usuarios/views.py
from django.shortcuts import render
from App_Usuarios.forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout as auth_logout
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
def registro(request):
    """
Vista para el registro de usuarios en RiskAgro.

    Parámetros:
        request (HttpRequest): La solicitud HTTP recibida por la vista.

    Returns:
        HttpResponse: Una respuesta HTTP que renderiza la plantilla 'signup.html' con un formulario de registro
                      o redirige al usuario a la página 'simulador' si el registro es exitoso.
    """
    if request.method == 'GET':
        Titulo = 'RiskAgro'
        return render(request, 'signup.html', {
            'form': CustomUserCreationForm, 'mensaje': Titulo
        })

    else:
        if request.POST['password1'] == request.POST['password2']:
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                try:
                    user = User.objects.create_user(
                        username=request.POST['username'], password=request.POST['password1'],
                        email=request.POST['email'], first_name=request.POST['nombres'], last_name=request.POST['apellidos'])
                    user.save()
                    login(request, user)
                    return redirect('simulador')
                except IntegrityError as e:
                    return render(request, 'signup.html',
                                  {'form': CustomUserCreationForm,
                                   'error_message': 'Este usuario ya se encuentra registrado', })
            else:
                return render(request, 'signup.html', {'form': form, })
        else:
            return render(request, 'signup.html',
                          {'form': CustomUserCreationForm,
                           'error_message': 'Contraseñas no coinciden',
                           })


def ingresar(request):
    """
Vista para iniciar sesión en RiskAgro.

    Parámetros:
        request (HttpRequest): La solicitud HTTP recibida por la vista.

    Returns:
        HttpResponse: Una respuesta HTTP que renderiza la plantilla 'signin.html' con un formulario de inicio de sesión
                      o redirige al usuario a la página 'simulador' si la autenticación es exitosa.
    """
    if request.method == 'GET':
        Titulo = 'RiskAgro'
        return render(request, 'login.html', {
            'form': AuthenticationForm, 'mensaje': Titulo,
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        print(request.POST)
        if user is None:
            return render(request, 'login.html', {
                'form': AuthenticationForm,
                'error_message': 'El nombre de usuario o contraseña es incorrecto',

            })
        else:
            login(request, user)
            return redirect('blog')


def logout(request):
    """
Vista para cerrar sesión en RiskAgro.

    Parámetros:
        request (HttpRequest): La solicitud HTTP recibida por la vista.

    Returns:
        HttpResponseRedirect: Una respuesta HTTP que redirige al usuario a la página de inicio ('inicio').
    """
    auth_logout(request)
    return redirect('inicio')


@login_required(login_url='login')
def perfil(request):
    """Vista para edit información del perfil y mostrar template

    Args:
        request (HttpRequest): request (HttpRequest): La solicitud HTTP recibida por la vista.

    Returns:
        None: La vista mediante GET devuelve el foprmulario con la instancia del objeto de 
        usuario identificado por request.user. Para el método POST devuelve un mensaje de confirmación en caso de que el formulario sea valido y se ejecute
        el metodo save()
    """
    confirm = 'Se han actualizado los datos'
    user = request.user
    etiqueta = 'Inicio'
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            # Redirige a la URL del perfil
            return render(request, 'perfil.html', {'form': form, 'etiqueta': etiqueta, 'user': user, 'confirm': confirm})
    else:
        form = CustomUserChangeForm(instance=user, initial={
                                    'nombres': user.first_name, 'apellidos': user.last_name, 'user': user})

    return render(request, 'perfil.html', {'form': form, 'etiqueta': etiqueta, 'user': user})

App_Usuarios/templates/login.html
{% extends 'base.html' %} 

# Primer bloque
{% block content1 %}
{% if user.is_authenticated %}
<a class="navbar-brand" href="/inicio">
    {{mensaje}} /
</a>
<a class="navbar-brand" href="/perfil">
{{user}}
</a>
{% else %}
<a class="navbar-brand" href="/inicio">
    {{mensaje}} 
</a>
{% endif %}
{% endblock %}

# Segundo bloque
{% block content2 %}
<div class="container">
    <p style="color: red;">{{error_message}}</p>
</div>
{% endblock %}

{% block contentbar %}
{% endblock %}

# Tercer bloque
{% block content3 %}
<div class="container">
  <h1>Ingresar</h1>
  <form method="POST" class ="mi-formulario" style="display: inline-block;">
    {% csrf_token %}
    <div class="mi-formulario">
      <label for="id_username">Usuario:</label>
      {{ form.username.errors }}
      {{ form.username }}
      <label for="id_password1">Contraseña:</label>
      {{ form.password.errors }}
      {{ form.password }}
    </div>
    <button type="submit" class = "btn btn-primary"  href="#" role="button">
      Signup
    </button>
  </form>
</div>
</form>
{% endblock %}

App_Usuarios/templates/perfil.html
{% extends 'base.html' %} 

# Primer bloque
{% block content1 %}
{% if user.is_authenticated %}
<a class="navbar-brand" href="/inicio">
    {{etiqueta}} /
</a>
<a class="navbar-brand" href="/perfil">
    {{user.username}} 
</a>

{% else %}
<a class="navbar-brand" href="/inicio">
    {{etiqueta}} 
</a>
{% endif %}
{% endblock %}

{% block contentbar %}
{% endblock %}

{% block content2 %}
{% if confirm %}
<div class="alert alert-success">{{confirm}}</div>
{% endif %}  
<form method="POST" class="mi-formulario">
    {% csrf_token %}
    <div class="mi-formulario">
        <label for="id_username">Usuario:</label>
            {{ form.username.errors }}
            {{ form.username }}  

        <label for="id_nombres">Nombres:</label>
        {{ form.first_name.errors }}
        {{ form.nombres }}

        <label for="id_apellidos">Apellidos:</label>
        {{ form.last_name.errors }}
        {{ form.apellidos }}

        <label for="id_email">Email:</label>
        {{ form.email.errors }}
        {{ form.email }}

        <label for="id_email">Contraseña:</label>
        {{ form.password1.errors }}
        {{ form.password1 }}

        <label for="id_email">Confirma la contraseña:</label>
        {{ form.password2.errors }}
        {{ form.password2 }}
    </div>
    <div class="boton-container">
      <button type="submit" class = "btn btn-primary"  href="#" role="button">
        Actualizar
      </button>
    </div>    
{% endblock %}

{% block content3 %}

{% endblock %}

App_Usuarios/templates/signup.html
{% extends 'base.html' %} 

# Primer bloque
{% block content1 %}
{% if user.is_authenticated %}
<a class="navbar-brand" href="/inicio">
    {{mensaje}} /
</a>
<a class="navbar-brand" href="/perfil">
{{user}}
</a>
{% else %}
<a class="navbar-brand" href="/inicio">
    {{mensaje}} 
</a>
{% endif %}
{% endblock %}

# Segundo bloque
{% block content2 %}
<div class="container">
  <p style="color: red;">{{error_message}}</p>
</div>
{% endblock %}

{% block contentbar %}
{% endblock %}

# Tercer bloque
{% block content3 %}
<div class="container">
  <h1>Registro</h1>
  <form method="POST" class="mi-formulario" style="display: inline-block;">
    {% csrf_token %}
    <div class="mi-formulario>
      <label for="id_username">Usuario:</label>
      {{ form.username.errors }}
      {{ form.username }}

      <label for="id_username">Nombres:</label>
      {{ form.username.errors }}
      {{ form.nombres }}

      <label for="id_username">Apellidos:</label>
      {{ form.username.errors }}
      {{ form.apellidos }}

      <label for="id_password1">Contraseña:</label>
      {{ form.password1.errors }}
      {{ form.password1 }}

      <label for="id_password2">Confirmacion:</label>
      {{ form.password2.errors }}
      {{ form.password2 }}

      <label for="id_email">Email:</label>
      {{ form.email.errors }}
      {{ form.email }}
    </div>
    <div class="boton-container">
      <button type="submit" class = "btn btn-primary"  href="#" role="button">
        Signup
      </button>
    </div>    

  </form>

</div>
</form>
{% endblock %}